FROM openjdk:8-jdk-alpine as build
MAINTAINER Bruno Barbosa da Silva 
RUN apk update && apk upgrade
ENV PORT=9090
WORKDIR /workspace/app
ADD  @project.build.finalName@.jar  ./
ENTRYPOINT java -Dserver.port=$PORT -jar @project.build.finalName@.jar